### ISSUE TITLE
[Feature] Set box witdth

### ISSUE THREAD

**Issue by JamesGalt** [ilgizar/ilgizar-candlestick-panel#1]
I dont know why but boxes are two wide
see screenshot
I'm using Grafana Version 4.6.3 (commit: 7a06a47)

<img width="1432" alt="capture d ecran 2018-02-22 a 00 55 20" src="https://user-images.githubusercontent.com/13592957/36512624-85b5d3b6-176b-11e8-979a-214ca8a122f3.png">
Thanks

**Comment by ilgizar** [comment]
I'm develop and test on 5.0.0-beta. 
The plans are to create a parameter that sets the width and number of boxes.

**Comment by JamesGalt** [comment]
It may come from there, does 5.0.0-beta is stable enough?
do you know how to migrate safely from 4.6.3 to 5.0.0?
the number of boxes is not set by the groupBY time?

**Comment by JamesGalt** [comment]
The problem comes from the fact I use a template variable for the groupBY interval so setting box width may come handy to avoid this issue. 
Are you using the __$interval hard coded in the panel?
You can also set the box width by dividing the width of the graph by the length of data.
This would make it dynamique so it's the best way I think. (like the bar view in the graph panel)

**Comment by ilgizar** [comment]
5.0.0-beta is unstable. I do not recommend yet to be updated, because no return.
Examples of query:
**open**: `SELECT first("open") FROM "ticker" WHERE ("market" =~ /^$market$/ AND "pair" =~ /^$pair$/) AND $timeFilter GROUP BY time($__interval) fill(linear)`
**close**: `SELECT last("close") FROM "ticker" WHERE ("market" =~ /^$market$/ AND "pair" =~ /^$pair$/) AND $timeFilter GROUP BY time($__interval) fill(linear)`
**low**: `SELECT min("low") FROM "ticker" WHERE ("market" =~ /^$market$/ AND "pair" =~ /^$pair$/) AND $timeFilter GROUP BY time($__interval) fill(linear)`
**high**: `SELECT max("high") FROM "ticker" WHERE ("market" =~ /^$market$/ AND "pair" =~ /^$pair$/) AND $timeFilter GROUP BY time($__interval) fill(linear)`
**volume**: `SELECT max("volume") FROM "ticker" WHERE ("market" =~ /^$market$/ AND "pair" =~ /^$pair$/) AND $timeFilter GROUP BY time($__interval) fill(linear)`

**Comment by JamesGalt** [comment]
I use the same queries, but it would be great to be able to use custom intervals. 
so the box width should be calculated using the value in the GROUP BY time(XXX) so it adjusts by itself.
Thanks

**Comment by JamesGalt** [comment]
Hi, Thanks, This is better but is it possible to set it dynamically (panel width / nb data points)?
I don't know how it is done in the graph panel but when you select bars drawing it adjusts by itself.
Thanks

**Comment by ilgizar** [comment]
Auto width by max data points. Candlestick width = panel width / max data points.

**Comment by JamesGalt** [comment]
I've seen that, but I'm talking about real auto, without setting max data points like in the graph panel
<img width="1436" alt="capture d ecran 2018-02-26 a 08 58 09" src="https://user-images.githubusercontent.com/13592957/36659008-48d71f34-1ad3-11e8-87f1-16706bb79b80.png">

look at the bars they auto adapt.
By the way thanks, i really appreciate the work. ;)

**Comment by JamesGalt** [comment]
I think in the graph panel it is related to [here](https://github.com/grafana/grafana/blob/c21d9deccb62873dbae9fb3483e7880aa9f03ed7/public/vendor/flot/jquery.flot.js#L1244)
and [there](https://github.com/grafana/grafana/blob/c21d9deccb62873dbae9fb3483e7880aa9f03ed7/public/vendor/flot/jquery.flot.js#L2685) for the drawing 
Not sure because I'm not a javascript wizard. I mostly do Python ;)

**Comment by ilgizar** [comment]
Try now autowidth.

**Comment by JamesGalt** [comment]
Perfect !!!!
🥇

**Comment by JamesGalt** [comment]
Last thing to be perfect, it should be aligned with the bar graph (I think you center the box and they dont in the bar graph)
see screenshot below
![capture d ecran 2018-02-26 a 18 35 47](https://user-images.githubusercontent.com/13592957/36685707-78c87660-1b24-11e8-8d00-c54fc2f8c8b1.png)
Impressive work by the way
